# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
