# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20160918_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=256, unique=True, verbose_name='e-mail'),
        ),
    ]
